# Generated by Django 3.1.5 on 2021-02-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_adresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='exterior_number',
            new_name='external_number',
        ),
    ]
